---
name: "Deploy Site"

"on":
  push:
    branches: ["main"]
    paths:
      - "site/**"
      - ".github/workflows/deploy-site.yml"

permissions:
  contents: "read"
  deployments: "write"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" # v4

      - name: "Setup Hugo"
        uses: "peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f" # v3
        with:
          hugo-version: "latest"
          extended: true

      - name: "Build"
        run: "hugo --minify -s site"

      - name: "Deploy to Cloudflare Pages"
        uses: "cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65" # v3
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          accountId: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          command: "pages deploy site/public --project-name=tgdash-garbas"
